package com.mycompany.proyectosisi;

import javax.swing.JOptionPane;

/**
 *
 * @author carlossalcidoa
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */

    public Interfaz() {
        this.setVisible(true);
        initComponents();
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio), true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear), false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta), false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar), false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelBoletos), false);
        CconexionBD objetoConexion = new CconexionBD();
        objetoConexion.establecerConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtInicioNom = new javax.swing.JTextField();
        txtInicioPassw = new javax.swing.JTextField();
        btnInicioIniciar = new javax.swing.JButton();
        btnInicioCrearC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnInicioSalir = new javax.swing.JButton();
        panelCrear = new javax.swing.JPanel();
        txtPassword1 = new javax.swing.JTextField();
        txtTarjeta1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        btnGuardarUsuario1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomUsr1 = new javax.swing.JTextField();
        btnCrearVolver = new javax.swing.JButton();
        panelOferta = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblOfertaGdlVall = new javax.swing.JLabel();
        lblOfertaGdlMaz = new javax.swing.JLabel();
        lblOfertaGdlTeq = new javax.swing.JLabel();
        lblOfertaGdlChp = new javax.swing.JLabel();
        lblOfertaGdlTep = new javax.swing.JLabel();
        cmbOfertaFechaGdlVall = new javax.swing.JComboBox<>();
        cmbOfertaFechaGdlMaz = new javax.swing.JComboBox<>();
        cmbOfertaFechaGdlTeq = new javax.swing.JComboBox<>();
        cmbOfertaFechaGdlChp = new javax.swing.JComboBox<>();
        cmbOfertaFechaGdlTep = new javax.swing.JComboBox<>();
        btnOfertaCerrar = new javax.swing.JButton();
        cmbOfertaHoraGdlVall = new javax.swing.JComboBox<>();
        cmbOfertaHoraGdlMaz = new javax.swing.JComboBox<>();
        cmbOfertaHoraGdlTeq = new javax.swing.JComboBox<>();
        cmbOfertaHoraGdlChp = new javax.swing.JComboBox<>();
        cmbOfertaHoraGdlTep = new javax.swing.JComboBox<>();
        txtOfertaCupoGdlVall = new javax.swing.JTextField();
        btnOfertaCupoGdlVall = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnOfertaComprarGdlVall = new javax.swing.JButton();
        btnOfertaCupoGdlChp = new javax.swing.JButton();
        btnOfertaCupoGdlMaz = new javax.swing.JButton();
        btnOfertaCupoGdlTeq = new javax.swing.JButton();
        btnOfertaCupoGdlTep = new javax.swing.JButton();
        txtOfertaCupoGdlMaz = new javax.swing.JTextField();
        txtOfertaCupoGdlTeq = new javax.swing.JTextField();
        txtOfertaCupoGdlChp = new javax.swing.JTextField();
        txtOfertaCupoGdlTep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnOfertaComprarGdlTeq = new javax.swing.JButton();
        btnOfertaComprarGdlMaz = new javax.swing.JButton();
        btnOfertaComprarGdlChp = new javax.swing.JButton();
        btnOfertaComprarGdlTep = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnOfertaBoletos = new javax.swing.JButton();
        panelComprar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtComprarDestino = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtComprarFecha = new javax.swing.JTextField();
        txtComprarHora = new javax.swing.JTextField();
        txtComprarPrecio = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtCompraCalcular = new javax.swing.JTextField();
        btnCompraCalcular = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        MXN = new javax.swing.JLabel();
        txtComprarReg = new javax.swing.JTextField();
        txtComprarEstd = new javax.swing.JTextField();
        btnCompraComprar = new javax.swing.JButton();
        btnCompraVolver = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtComprarUsuario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtComprarNombreViaj = new javax.swing.JTextField();
        btnCompraBoletos = new javax.swing.JButton();
        panelBoletos = new javax.swing.JPanel();
        btnBoletosVolver = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        btnBoletosCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoletosBoletos = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInicio.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AUTOCARS");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Nombre de Usuario:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");

        btnInicioIniciar.setText("INICIAR");
        btnInicioIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioIniciarActionPerformed(evt);
            }
        });

        btnInicioCrearC.setText("CREAR UNA CUENTA");
        btnInicioCrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioCrearCActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿No tienes una cuenta? Crea una aquí");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("La forma más segura de viajar");

        btnInicioSalir.setText("SALIR");
        btnInicioSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnInicioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(txtInicioNom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)))
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addComponent(btnInicioCrearC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(txtInicioPassw, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                        .addComponent(btnInicioIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(475, 475, 475))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(468, 468, 468))))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(99, 99, 99)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInicioNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInicioPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(72, 72, 72)
                .addComponent(btnInicioIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicioCrearC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                        .addComponent(btnInicioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );

        jTabbedPane2.addTab("INICIO", panelInicio);

        panelCrear.setBackground(new java.awt.Color(204, 0, 0));

        btnGuardarUsuario1.setText("GUARDAR");
        btnGuardarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuario1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear Usuario Nuevo");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre de Usuario:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Escribe una Contraseña:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Escribe tu correo electrónico:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingresa tu Tarjeta:");

        btnCrearVolver.setText("VOLVER");
        btnCrearVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel6))
                    .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrearLayout.createSequentialGroup()
                            .addGap(455, 455, 455)
                            .addComponent(btnGuardarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                            .addComponent(btnCrearVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCrearLayout.createSequentialGroup()
                            .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelCrearLayout.createSequentialGroup()
                                    .addGap(246, 246, 246)
                                    .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(56, 56, 56))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCrearLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9))
                                    .addGap(18, 18, 18)))
                            .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(txtNomUsr1)
                                .addComponent(txtTarjeta1)
                                .addComponent(txtEmail1)))))
                .addContainerGap(377, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomUsr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );

        jTabbedPane2.addTab("CREAR CUENTA", panelCrear);

        panelOferta.setBackground(new java.awt.Color(204, 0, 0));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OFERTA DE VIAJES");

        lblOfertaGdlVall.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOfertaGdlVall.setForeground(new java.awt.Color(255, 255, 255));
        lblOfertaGdlVall.setText("GUADALAJARA - VALLARTA");

        lblOfertaGdlMaz.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOfertaGdlMaz.setForeground(new java.awt.Color(255, 255, 255));
        lblOfertaGdlMaz.setText("GUADALAJARA - MAZAMITLA");

        lblOfertaGdlTeq.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOfertaGdlTeq.setForeground(new java.awt.Color(255, 255, 255));
        lblOfertaGdlTeq.setText("GUADALAJARA - TEQUILA");

        lblOfertaGdlChp.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOfertaGdlChp.setForeground(new java.awt.Color(255, 255, 255));
        lblOfertaGdlChp.setText("GUADALAJARA - CHAPALA");

        lblOfertaGdlTep.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblOfertaGdlTep.setForeground(new java.awt.Color(255, 255, 255));
        lblOfertaGdlTep.setText("GUADALAJARA - TEPATITLÁN");

        cmbOfertaFechaGdlVall.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaFechaGdlVall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/DICIEMBRE", "11/DICIEMBRE", "12/DICIEMBRE" }));

        cmbOfertaFechaGdlMaz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaFechaGdlMaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/DICIEMBRE", "11/DICIEMBRE", "12/DICIEMBRE" }));

        cmbOfertaFechaGdlTeq.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaFechaGdlTeq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/DICIEMBRE", "11/DICIEMBRE", "12/DICIEMBRE" }));

        cmbOfertaFechaGdlChp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaFechaGdlChp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/DICIEMBRE", "11/DICIEMBRE", "12/DICIEMBRE" }));

        cmbOfertaFechaGdlTep.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaFechaGdlTep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10/DICIEMBRE", "11/DICIEMBRE", "12/DICIEMBRE" }));

        btnOfertaCerrar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCerrar.setText("CERRAR SESIÓN");
        btnOfertaCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCerrarActionPerformed(evt);
            }
        });

        cmbOfertaHoraGdlVall.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaHoraGdlVall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        cmbOfertaHoraGdlMaz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaHoraGdlMaz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        cmbOfertaHoraGdlTeq.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaHoraGdlTeq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        cmbOfertaHoraGdlChp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaHoraGdlChp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        cmbOfertaHoraGdlTep.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cmbOfertaHoraGdlTep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "15:00", "20:00" }));

        txtOfertaCupoGdlVall.setText("40");
        txtOfertaCupoGdlVall.setEnabled(false);
        txtOfertaCupoGdlVall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfertaCupoGdlVallActionPerformed(evt);
            }
        });

        btnOfertaCupoGdlVall.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCupoGdlVall.setText("VER CUPO");
        btnOfertaCupoGdlVall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCupoGdlVallActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$600MXN");

        btnOfertaComprarGdlVall.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaComprarGdlVall.setText("COMPRAR");
        btnOfertaComprarGdlVall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaComprarGdlVallActionPerformed(evt);
            }
        });

        btnOfertaCupoGdlChp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCupoGdlChp.setText("VER CUPO");
        btnOfertaCupoGdlChp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCupoGdlChpActionPerformed(evt);
            }
        });

        btnOfertaCupoGdlMaz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCupoGdlMaz.setText("VER CUPO");
        btnOfertaCupoGdlMaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCupoGdlMazActionPerformed(evt);
            }
        });

        btnOfertaCupoGdlTeq.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCupoGdlTeq.setText("VER CUPO");
        btnOfertaCupoGdlTeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCupoGdlTeqActionPerformed(evt);
            }
        });

        btnOfertaCupoGdlTep.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaCupoGdlTep.setText("VER CUPO");
        btnOfertaCupoGdlTep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaCupoGdlTepActionPerformed(evt);
            }
        });

        txtOfertaCupoGdlMaz.setText("40");
        txtOfertaCupoGdlMaz.setEnabled(false);

        txtOfertaCupoGdlTeq.setText("40");
        txtOfertaCupoGdlTeq.setEnabled(false);

        txtOfertaCupoGdlChp.setText("40");
        txtOfertaCupoGdlChp.setEnabled(false);

        txtOfertaCupoGdlTep.setText("40");
        txtOfertaCupoGdlTep.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("$200MXN");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("$120MXN");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("$80MXN");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("$70MXN");

        btnOfertaComprarGdlTeq.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaComprarGdlTeq.setText("COMPRAR");
        btnOfertaComprarGdlTeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaComprarGdlTeqActionPerformed(evt);
            }
        });

        btnOfertaComprarGdlMaz.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaComprarGdlMaz.setText("COMPRAR");
        btnOfertaComprarGdlMaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaComprarGdlMazActionPerformed(evt);
            }
        });

        btnOfertaComprarGdlChp.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaComprarGdlChp.setText("COMPRAR");
        btnOfertaComprarGdlChp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaComprarGdlChpActionPerformed(evt);
            }
        });

        btnOfertaComprarGdlTep.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaComprarGdlTep.setText("COMPRAR");
        btnOfertaComprarGdlTep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaComprarGdlTepActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("FECHAS");

        jLabel29.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("HORARIOS");

        btnOfertaBoletos.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnOfertaBoletos.setText("VER MIS COMPRAS");
        btnOfertaBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaBoletosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOfertaLayout = new javax.swing.GroupLayout(panelOferta);
        panelOferta.setLayout(panelOfertaLayout);
        panelOfertaLayout.setHorizontalGroup(
            panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOfertaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(463, 463, 463))
            .addGroup(panelOfertaLayout.createSequentialGroup()
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOfertaLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOfertaCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelOfertaLayout.createSequentialGroup()
                                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOfertaGdlVall)
                                    .addComponent(lblOfertaGdlMaz)
                                    .addComponent(lblOfertaGdlTeq)
                                    .addComponent(lblOfertaGdlChp)
                                    .addComponent(lblOfertaGdlTep))
                                .addGap(45, 45, 45)
                                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbOfertaFechaGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbOfertaFechaGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbOfertaFechaGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbOfertaFechaGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbOfertaFechaGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOfertaLayout.createSequentialGroup()
                                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(cmbOfertaHoraGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOfertaCupoGdlTep))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(cmbOfertaHoraGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnOfertaCupoGdlChp))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(cmbOfertaHoraGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOfertaCupoGdlVall))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbOfertaHoraGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbOfertaHoraGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnOfertaCupoGdlTeq)
                                            .addComponent(btnOfertaCupoGdlMaz))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(txtOfertaCupoGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOfertaComprarGdlVall))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(txtOfertaCupoGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOfertaComprarGdlMaz))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(txtOfertaCupoGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOfertaComprarGdlTeq))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(txtOfertaCupoGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOfertaComprarGdlChp))
                                    .addGroup(panelOfertaLayout.createSequentialGroup()
                                        .addComponent(txtOfertaCupoGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOfertaComprarGdlTep))))
                            .addGroup(panelOfertaLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(btnOfertaBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelOfertaLayout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel28)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel29)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        panelOfertaLayout.setVerticalGroup(
            panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOfertaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel11)
                .addGap(125, 125, 125)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfertaGdlVall)
                    .addComponent(cmbOfertaFechaGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOfertaHoraGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOfertaCupoGdlVall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaCupoGdlVall)
                    .addComponent(jLabel12)
                    .addComponent(btnOfertaComprarGdlVall))
                .addGap(34, 34, 34)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfertaGdlMaz)
                    .addComponent(cmbOfertaFechaGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOfertaHoraGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaCupoGdlMaz)
                    .addComponent(txtOfertaCupoGdlMaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnOfertaComprarGdlMaz))
                .addGap(38, 38, 38)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfertaGdlTeq)
                    .addComponent(cmbOfertaFechaGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOfertaHoraGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaCupoGdlTeq)
                    .addComponent(txtOfertaCupoGdlTeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnOfertaComprarGdlTeq))
                .addGap(34, 34, 34)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfertaGdlChp)
                    .addComponent(cmbOfertaFechaGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOfertaHoraGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaCupoGdlChp)
                    .addComponent(txtOfertaCupoGdlChp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btnOfertaComprarGdlChp))
                .addGap(35, 35, 35)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfertaGdlTep)
                    .addComponent(cmbOfertaFechaGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOfertaHoraGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaCupoGdlTep)
                    .addComponent(txtOfertaCupoGdlTep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btnOfertaComprarGdlTep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panelOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOfertaCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOfertaBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jTabbedPane2.addTab("OFERTA DE VIAJES", panelOferta);

        panelComprar.setBackground(new java.awt.Color(204, 0, 0));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Comprar Viaje");

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Destino:");

        txtComprarDestino.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha:");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Hora:");

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Precio:");

        txtComprarFecha.setEnabled(false);

        txtComprarHora.setEnabled(false);

        txtComprarPrecio.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Escribe los últimos datos para completar tu compra");

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("¿Cuántos asientos de Estudiante?");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("¿Cuántos asientos regulares?");

        txtCompraCalcular.setEnabled(false);
        txtCompraCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompraCalcularActionPerformed(evt);
            }
        });

        btnCompraCalcular.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCompraCalcular.setText("VER PRECIO TOTAL");
        btnCompraCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraCalcularActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("$");

        MXN.setForeground(new java.awt.Color(255, 255, 255));
        MXN.setText("MXN");

        txtComprarReg.setText("0");

        txtComprarEstd.setText("0");

        btnCompraComprar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCompraComprar.setText("COMPRAR ESTE VIAJE");
        btnCompraComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraComprarActionPerformed(evt);
            }
        });

        btnCompraVolver.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCompraVolver.setText("VOLVER A LA OFERTA");
        btnCompraVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraVolverActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Usuario:");

        txtComprarUsuario.setEnabled(false);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Nombre de la persona que viaja:");

        btnCompraBoletos.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCompraBoletos.setText("VER MIS COMPRAS");
        btnCompraBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraBoletosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComprarLayout = new javax.swing.GroupLayout(panelComprar);
        panelComprar.setLayout(panelComprarLayout);
        panelComprarLayout.setHorizontalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelComprarLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtComprarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelComprarLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtComprarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelComprarLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                            .addComponent(txtComprarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelComprarLayout.createSequentialGroup()
                        .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComprarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComprarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComprarLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel17))
                    .addGroup(panelComprarLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelComprarLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtComprarEstd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelComprarLayout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(59, 59, 59)
                                    .addComponent(txtComprarReg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelComprarLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addGroup(panelComprarLayout.createSequentialGroup()
                                .addComponent(btnCompraComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(panelComprarLayout.createSequentialGroup()
                                .addComponent(btnCompraCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCompraCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                        .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelComprarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtComprarNombreViaj, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelComprarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(MXN))))
                    .addGroup(panelComprarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCompraVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnCompraBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, 173))
        );
        panelComprarLayout.setVerticalGroup(
            panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComprarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel17)
                .addGap(73, 73, 73)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(txtComprarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtComprarReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComprarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtComprarEstd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtComprarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtComprarHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtComprarNombreViaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtComprarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompraCalcular)
                    .addComponent(txtCompraCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(MXN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnCompraComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(panelComprarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompraVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompraBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jTabbedPane2.addTab("COMPRAR", panelComprar);

        panelBoletos.setBackground(new java.awt.Color(204, 0, 0));
        panelBoletos.setEnabled(false);

        btnBoletosVolver.setText("VOLVER A LA OFERTA");
        btnBoletosVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosVolverActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Boletos Comprados");

        btnBoletosCerrar.setText("CERRAR SESIÓN");
        btnBoletosCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoletosCerrarActionPerformed(evt);
            }
        });

        tblBoletosBoletos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBoletosBoletos);

        javax.swing.GroupLayout panelBoletosLayout = new javax.swing.GroupLayout(panelBoletos);
        panelBoletos.setLayout(panelBoletosLayout);
        panelBoletosLayout.setHorizontalGroup(
            panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBoletosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(505, 505, 505))
            .addGroup(panelBoletosLayout.createSequentialGroup()
                .addGroup(panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBoletosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBoletosLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(btnBoletosVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnBoletosCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelBoletosLayout.setVerticalGroup(
            panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBoletosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel30)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBoletosVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnBoletosCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        jTabbedPane2.addTab("BOLETOS", panelBoletos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSalirActionPerformed
         int valor = JOptionPane.showConfirmDialog(this,"¿Estás seguro de que quieres salir del sistema?","Advertencia",JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Gracias por usar.");
            System.exit(0);
        }
    }//GEN-LAST:event_btnInicioSalirActionPerformed

    private void btnInicioCrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioCrearCActionPerformed
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_btnInicioCrearCActionPerformed

    private void btnCrearVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVolverActionPerformed
        txtNomUsr1.setText("");
        txtPassword1.setText("");
        txtEmail1.setText("");
        txtTarjeta1.setText("");
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
        jTabbedPane2.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnCrearVolverActionPerformed

    private void btnInicioIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioIniciarActionPerformed
        boolean login;
        Cclientes objetoClientes = new Cclientes();
        login =  objetoClientes.login(txtInicioNom, txtInicioPassw);
        if(login==true){
            txtComprarUsuario.setText(txtInicioNom.getText());
            
            txtInicioNom.setText("");
            txtInicioPassw.setText("");
        
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),true);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(2);
        }
    }//GEN-LAST:event_btnInicioIniciarActionPerformed

    private void btnGuardarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuario1ActionPerformed
        Cclientes objetoClietnes = new Cclientes();
        objetoClietnes.insertarCliente(txtNomUsr1, txtEmail1, txtEmail1, txtTarjeta1);
        
    }//GEN-LAST:event_btnGuardarUsuario1ActionPerformed

    private void btnOfertaCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCerrarActionPerformed
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
        jTabbedPane2.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnOfertaCerrarActionPerformed

    private void txtCompraCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompraCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraCalcularActionPerformed

    private void btnCompraVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraVolverActionPerformed
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_btnCompraVolverActionPerformed

    private void btnOfertaComprarGdlVallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaComprarGdlVallActionPerformed
        if(txtOfertaCupoGdlVall.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay más cupos disponibles");
        }
        else{
            txtComprarDestino.setText("GDL-VALLARTA");
            txtComprarFecha.setText(cmbOfertaFechaGdlVall.getSelectedItem().toString());
            txtComprarHora.setText(cmbOfertaHoraGdlVall.getSelectedItem().toString());
            txtComprarPrecio.setText("600");
            
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnOfertaComprarGdlVallActionPerformed

    private void btnOfertaComprarGdlMazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaComprarGdlMazActionPerformed
        if(txtOfertaCupoGdlMaz.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay más cupos disponibles");
        }
        else{
            txtComprarDestino.setText("GDL-MAZAMITLA");
            txtComprarFecha.setText(cmbOfertaFechaGdlMaz.getSelectedItem().toString());
            txtComprarHora.setText(cmbOfertaHoraGdlMaz.getSelectedItem().toString());
            txtComprarPrecio.setText("200");
            
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnOfertaComprarGdlMazActionPerformed

    private void btnOfertaComprarGdlTeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaComprarGdlTeqActionPerformed
        if(txtOfertaCupoGdlTeq.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay más cupos disponibles");
        }
        else{
            txtComprarDestino.setText("GDL-TEQUILA");
            txtComprarFecha.setText(cmbOfertaFechaGdlTeq.getSelectedItem().toString());
            txtComprarHora.setText(cmbOfertaHoraGdlTeq.getSelectedItem().toString());
            txtComprarPrecio.setText("120");
            
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnOfertaComprarGdlTeqActionPerformed

    private void btnOfertaComprarGdlChpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaComprarGdlChpActionPerformed
        if(txtOfertaCupoGdlChp.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay más cupos disponibles");
        }
        else{
            txtComprarDestino.setText("GDL-CHAPALA");
            txtComprarFecha.setText(cmbOfertaFechaGdlChp.getSelectedItem().toString());
            txtComprarHora.setText(cmbOfertaHoraGdlChp.getSelectedItem().toString());
            txtComprarPrecio.setText("80");
            
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnOfertaComprarGdlChpActionPerformed

    private void btnOfertaComprarGdlTepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaComprarGdlTepActionPerformed
        if(txtOfertaCupoGdlTep.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "No hay más cupos disponibles");
        }
        else{
            txtComprarDestino.setText("GDL-TEPATITLAN");
            txtComprarFecha.setText(cmbOfertaFechaGdlTep.getSelectedItem().toString());
            txtComprarHora.setText(cmbOfertaHoraGdlTep.getSelectedItem().toString());
            txtComprarPrecio.setText("70");
            
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
            jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
            jTabbedPane2.setSelectedIndex(3);
        }
    }//GEN-LAST:event_btnOfertaComprarGdlTepActionPerformed

    private void txtOfertaCupoGdlVallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfertaCupoGdlVallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfertaCupoGdlVallActionPerformed

    private void btnCompraComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraComprarActionPerformed
        Cclientes objetoClientes = new Cclientes();
        boolean guardar = objetoClientes.modificarCupo(txtComprarReg, txtComprarEstd, txtComprarDestino, txtComprarFecha, txtComprarHora);
        if(guardar == true){
            objetoClientes.insertarCompra(txtComprarUsuario, txtComprarNombreViaj, txtComprarReg, txtComprarEstd, txtComprarPrecio, 
                    txtComprarDestino, txtComprarFecha, txtComprarHora);
        }
        txtComprarReg.setText("");
        txtComprarEstd.setText("");
        txtComprarNombreViaj.setText("");
    }//GEN-LAST:event_btnCompraComprarActionPerformed

    private void btnOfertaCupoGdlVallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCupoGdlVallActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String cupo = objetoClientes.verCupo("GDL-VALLARTA", cmbOfertaFechaGdlVall.getSelectedItem().toString(), cmbOfertaHoraGdlVall.getSelectedItem().toString());
        txtOfertaCupoGdlVall.setText(cupo);
        
    }//GEN-LAST:event_btnOfertaCupoGdlVallActionPerformed

    private void btnOfertaCupoGdlMazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCupoGdlMazActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String cupo = objetoClientes.verCupo("GDL-MAZAMITLA", cmbOfertaFechaGdlMaz.getSelectedItem().toString(), cmbOfertaHoraGdlMaz.getSelectedItem().toString());
        txtOfertaCupoGdlMaz.setText(cupo);
        
    }//GEN-LAST:event_btnOfertaCupoGdlMazActionPerformed

    private void btnOfertaCupoGdlTeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCupoGdlTeqActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String cupo = objetoClientes.verCupo("GDL-TEQUILA", cmbOfertaFechaGdlTeq.getSelectedItem().toString(), cmbOfertaHoraGdlTeq.getSelectedItem().toString());
        txtOfertaCupoGdlTeq.setText(cupo);
    }//GEN-LAST:event_btnOfertaCupoGdlTeqActionPerformed

    private void btnOfertaCupoGdlChpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCupoGdlChpActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String cupo = objetoClientes.verCupo("GDL-CHAPALA", cmbOfertaFechaGdlChp.getSelectedItem().toString(), cmbOfertaHoraGdlChp.getSelectedItem().toString());
        txtOfertaCupoGdlChp.setText(cupo);
    }//GEN-LAST:event_btnOfertaCupoGdlChpActionPerformed

    private void btnOfertaCupoGdlTepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaCupoGdlTepActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String cupo = objetoClientes.verCupo("GDL-TEPATITLAN", cmbOfertaFechaGdlTep.getSelectedItem().toString(), cmbOfertaHoraGdlTep.getSelectedItem().toString());
        txtOfertaCupoGdlTep.setText(cupo);
    }//GEN-LAST:event_btnOfertaCupoGdlTepActionPerformed

    private void btnCompraBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraBoletosActionPerformed
        Cclientes objetoClientes = new Cclientes();
        objetoClientes.mostrarTabla(tblBoletosBoletos, txtComprarUsuario);
        
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelBoletos), true);
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_btnCompraBoletosActionPerformed

    private void btnOfertaBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaBoletosActionPerformed
        Cclientes objetoClientes = new Cclientes();
        objetoClientes.mostrarTabla(tblBoletosBoletos, txtComprarUsuario);
        
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelBoletos), true);
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_btnOfertaBoletosActionPerformed

    private void btnCompraCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraCalcularActionPerformed
        Cclientes objetoClientes = new Cclientes();
        String precio = objetoClientes.verPrecio(txtComprarReg, txtComprarEstd, txtComprarPrecio);
        txtCompraCalcular.setText(precio);
        
    }//GEN-LAST:event_btnCompraCalcularActionPerformed

    private void btnBoletosCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosCerrarActionPerformed
         jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelBoletos), false);
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_btnBoletosCerrarActionPerformed

    private void btnBoletosVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletosVolverActionPerformed
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelInicio),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelCrear),false);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelOferta),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelComprar),true);
        jTabbedPane2.setEnabledAt(jTabbedPane2.indexOfComponent(panelBoletos), true);
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_btnBoletosVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MXN;
    private javax.swing.JButton btnBoletosCerrar;
    private javax.swing.JButton btnBoletosVolver;
    private javax.swing.JButton btnCompraBoletos;
    private javax.swing.JButton btnCompraCalcular;
    private javax.swing.JButton btnCompraComprar;
    private javax.swing.JButton btnCompraVolver;
    private javax.swing.JButton btnCrearVolver;
    private javax.swing.JButton btnGuardarUsuario1;
    private javax.swing.JButton btnInicioCrearC;
    private javax.swing.JButton btnInicioIniciar;
    private javax.swing.JButton btnInicioSalir;
    private javax.swing.JButton btnOfertaBoletos;
    private javax.swing.JButton btnOfertaCerrar;
    private javax.swing.JButton btnOfertaComprarGdlChp;
    private javax.swing.JButton btnOfertaComprarGdlMaz;
    private javax.swing.JButton btnOfertaComprarGdlTep;
    private javax.swing.JButton btnOfertaComprarGdlTeq;
    private javax.swing.JButton btnOfertaComprarGdlVall;
    private javax.swing.JButton btnOfertaCupoGdlChp;
    private javax.swing.JButton btnOfertaCupoGdlMaz;
    private javax.swing.JButton btnOfertaCupoGdlTep;
    private javax.swing.JButton btnOfertaCupoGdlTeq;
    private javax.swing.JButton btnOfertaCupoGdlVall;
    private javax.swing.JComboBox<String> cmbOfertaFechaGdlChp;
    private javax.swing.JComboBox<String> cmbOfertaFechaGdlMaz;
    private javax.swing.JComboBox<String> cmbOfertaFechaGdlTep;
    private javax.swing.JComboBox<String> cmbOfertaFechaGdlTeq;
    private javax.swing.JComboBox<String> cmbOfertaFechaGdlVall;
    private javax.swing.JComboBox<String> cmbOfertaHoraGdlChp;
    private javax.swing.JComboBox<String> cmbOfertaHoraGdlMaz;
    private javax.swing.JComboBox<String> cmbOfertaHoraGdlTep;
    private javax.swing.JComboBox<String> cmbOfertaHoraGdlTeq;
    private javax.swing.JComboBox<String> cmbOfertaHoraGdlVall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblOfertaGdlChp;
    private javax.swing.JLabel lblOfertaGdlMaz;
    private javax.swing.JLabel lblOfertaGdlTep;
    private javax.swing.JLabel lblOfertaGdlTeq;
    private javax.swing.JLabel lblOfertaGdlVall;
    private javax.swing.JPanel panelBoletos;
    private javax.swing.JPanel panelComprar;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelOferta;
    private javax.swing.JTable tblBoletosBoletos;
    private javax.swing.JTextField txtCompraCalcular;
    private javax.swing.JTextField txtComprarDestino;
    private javax.swing.JTextField txtComprarEstd;
    private javax.swing.JTextField txtComprarFecha;
    private javax.swing.JTextField txtComprarHora;
    private javax.swing.JTextField txtComprarNombreViaj;
    private javax.swing.JTextField txtComprarPrecio;
    private javax.swing.JTextField txtComprarReg;
    private javax.swing.JTextField txtComprarUsuario;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtInicioNom;
    private javax.swing.JTextField txtInicioPassw;
    private javax.swing.JTextField txtNomUsr1;
    private javax.swing.JTextField txtOfertaCupoGdlChp;
    private javax.swing.JTextField txtOfertaCupoGdlMaz;
    private javax.swing.JTextField txtOfertaCupoGdlTep;
    private javax.swing.JTextField txtOfertaCupoGdlTeq;
    private javax.swing.JTextField txtOfertaCupoGdlVall;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtTarjeta1;
    // End of variables declaration//GEN-END:variables
}
